[package]
name = "compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
koopa = "0.0.8"
lalrpop-util = { version = "0.21.0", features = ["lexer", "unicode"] }

[build-dependencies]
lalrpop = "0.22.2"
